### ISSUE TITLE
what sites are crawled?

### ISSUE THREAD

**Issue by thebucketmouse** [google/corpuscrawler#43]
I looked through the readme; is there a list of what sites are crawled by this script? Is there documentation for how to add additional sites?

**Comment by brawer** [comment]
Have a look at the [source code](https://github.com/googlei18n/corpuscrawler/tree/master/Lib/corpuscrawler) and follow the examples. They typically use utility functions from [here](https://github.com/googlei18n/corpuscrawler/blob/master/Lib/corpuscrawler/util.py).

**Comment by sffc** [comment]
Closing as there is no further action required on this issue. Feel free to submit a PR updating the documentation.
