### ISSUE TITLE
Documentation > Clarify language codes system in uses

### ISSUE THREAD

**Issue by hugolpz** [google/corpuscrawler#83]
Tiny issue : add a reference to the language code system you use.

I may have missed it.

See also : https://en.wikipedia.org/wiki/Language_code

**Comment by brawer** [comment]
It’s IETF language tags. Same coding system as used by HTML, XML, and almost everything else on the internet.

**Comment by hugolpz** [comment]
It's consistent ? 100% of the name use this convention ?

**Comment by brawer** [comment]
The [README file](https://github.com/google/corpuscrawler) already says “IETF BCP47”. Yes, they should be consistent; are you aware of any cases that aren’t IETF language tags?

**Comment by hugolpz** [comment]
Thank. I reported it onto [LinguaLibre:Language_codes_systems_used_across_LinguaLibre](https://lingualibre.org/wiki/LinguaLibre:Language_codes_systems_used_across_LinguaLibre)
